In [1]:
import pandas as pd
import numpy as np

# Question 1
A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between 
two units. A randomly selected sample of cutlets was collected from both units and measured? Analyze the data and 
draw inferences at 5% significance level. Please state the assumptions and tests that you carried out to check 
validity of the assumptions.


In [3]:
df=pd.read_csv("D:\ExcelR Data Science\Assignments\Hypothesis Testing\Cutlets.csv")
df.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [4]:
df.shape

(35, 2)

In [5]:
df.describe()

Unit A     Unit B
count  35.000000  35.000000
mean    7.019091   6.964297
std     0.288408   0.343401
min     6.437600   6.038000
25%     6.831500   6.753600
50%     6.943800   6.939900
75%     7.280550   7.195000
max     7.516900   7.545900

####  2Tailed t- Test
     We need to check whether the mean of both samples are different and
     Is there any significance difference between the two samples?
     H0: m1=m2
     H1:m1nt equal to m2
     

In [7]:
import scipy.stats as stats

In [8]:
p_value=stats.ttest_ind(df['Unit A'],df['Unit B'])

In [10]:
p_value[1]

0.4722394724599501

Compare p_value with alpha '(Significane Level)
If p_value notequal to alpha is 
we failed to reject Null Hypothesis because of lack of evidence


If p_value is equal to alphs'
 we reject Null Hypothesis

In [16]:
alpha = 0.025
print('Significnace=%.3f, p=%.3f' % (alpha, p_value[1]))
if p_value[1] <= alpha:
        print('We reject Null Hypothesis there is a significance difference between two Units A and B')
else:
    print('We fail to reject Null hypothesis')

Significnace=0.025, p=0.472
We fail to reject Null hypothesis


### Hence, We fail to reject Null Hypothesis because of lack of evidence, there is no significant difference between the two samples

### Question2
A hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) of reports of the laboratories on their preferred list. They collected a random sample and recorded TAT for reports of 4 laboratories. TAT is defined as sample collected to report dispatch.
   
  Analyze the data and determine whether there is any difference in average TAT among the different laboratories at 5% significance level.


In [17]:
df1=pd.read_csv("D:\ExcelR Data Science\Assignments\Hypothesis Testing\LabTAT.csv")
df1.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

### ANOVA TEST
       Make two Hypothesis one contradicting to other
       Null Hypothesis is want we want to prove
       Null Hypothesis: m1=m2=m3=m4
       Alternative Hypthosis: Atleast One of them is Differente

In [19]:
df1.isnull().sum()

Laboratory 1    0
Laboratory 2    0
Laboratory 3    0
Laboratory 4    0
dtype: int64

In [21]:
df1.shape

(120, 4)

In [22]:
df1.describe()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
count    120.000000    120.000000    120.000000     120.00000
mean     178.361583    178.902917    199.913250     163.68275
std       13.173594     14.957114     16.539033      15.08508
min      138.300000    140.550000    159.690000     124.06000
25%      170.335000    168.025000    188.232500     154.05000
50%      178.530000    178.870000    199.805000     164.42500
75%      186.535000    189.112500    211.332500     172.88250
max      216.390000    217.860000    238.700000     205.18000

In [31]:
test_statistic , p_value = stats.f_oneway(df1['Laboratory 1'],df1['Laboratory 2'],df1['Laboratory 3'],df1['Laboratory 4'])

In [32]:
print('P_value',p_value)

P_value 2.1156708949992414e-57


In [37]:
alpha = 0.05
print('Significnace=%.3f, p=%.3f' % (alpha, p_value))
if p_value <= alpha:
        print('We reject Null Hypothesis there is a significance difference between two Units A and B')
else:
    print('We fail to reject Null hypothesis')

Significnace=0.050, p=0.000
We reject Null Hypothesis there is a significance difference between two Units A and B


### Question3-Hypothesis Testing
### CHI Square
Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions.


In [38]:
df3=pd.read_csv("D:\ExcelR Data Science\Assignments\Hypothesis Testing\BuyerRatio.csv")
df3.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

# 
     H0:There is no dependency between gender based buyer across regions
     H1: There is dependency between gender based buyer across regions

In [41]:
stat, p, dof, exp = stats.chi2_contingency(df3.iloc[:,1:5]) 
print(stat,"\n", p,"\n", dof,"\n", exp)

1.595945538661058 
 0.6603094907091882 
 3 
 [[  42.76531299  146.81287862  131.11756787   72.30424052]
 [ 442.23468701 1518.18712138 1355.88243213  747.69575948]]


In [42]:
observed = np.array([50, 142, 131, 70, 435, 1523, 1356, 750])
expected = np.array([42.76531299,  146.81287862,  131.11756787, 72.30424052, 442.23468701, 1518.18712138, 1355.88243213, 747.69575948])

In [43]:
statistics, p_value = stats.chisquare(observed, expected, ddof = 3)
print("Statistics = ",statistics,"\n",'P_Value = ', p_value)

Statistics =  1.5959455390914483 
 P_Value =  0.8095206646905712


In [44]:
alpha = 0.05
print('Significnace=%.3f, p=%.3f' % (alpha, p_value))
if p_value <= alpha:
        print('We reject Null Hypothesis there is a significance difference between two Units A and B')
else:
    print('We fail to reject Null hypothesis')

Significnace=0.050, p=0.810
We fail to reject Null hypothesis


# Question4
## Chi Square
     TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain %  of the customer order forms. Any error in order form renders it defective and has to be reworked before processing.  The manager wants to check whether the defective %  varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences


In [46]:
df4=pd.read_csv("D:\ExcelR Data Science\Assignments\Hypothesis Testing\Costomer+OrderForm.csv")
df4.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [51]:
print("Value COunts\n",df4['Phillippines'].value_counts())
print("Value COunts\n",df4['Indonesia'].value_counts())
print("Value COunts\n",df4['Malta'].value_counts())
print("Value COunts\n",df4['India'].value_counts())

Value COunts
 Error Free    271
Defective      29
Name: Phillippines, dtype: int64
Value COunts
 Error Free    267
Defective      33
Name: Indonesia, dtype: int64
Value COunts
 Error Free    269
Defective      31
Name: Malta, dtype: int64
Value COunts
 Error Free    280
Defective      20
Name: India, dtype: int64


In [52]:
table=[[271,267,269,280],[29,33,31,20]]

In [53]:
stat, p, dof, exp = stats.chi2_contingency(table) 
print(stat,"\n", p,"\n", dof,"\n", exp)

3.858960685820355 
 0.2771020991233135 
 3 
 [[271.75 271.75 271.75 271.75]
 [ 28.25  28.25  28.25  28.25]]


In [54]:
observed = np.array([271, 267, 269, 280, 29, 33, 31, 20])
expected = np.array([271.75, 271.75, 271.75, 271.75, 28.25, 28.25, 28.25, 28.25])

In [57]:
statistics, p_value = stats.chisquare(observed, expected, ddof = 3)
print("Statistics = ",statistics,"\n",'P_Value = ', p_value)

Statistics =  3.858960685820355 
 P_Value =  0.4254298144535761


In [60]:
alpha = 0.05
print('Significnace=%.3f, p=%.3f' % (alpha, p_value))
if p_value <= alpha:
        print('We reject Null Hypothesis there is a significance difference between two Units A and B')
else:
    print('We fail to reject Null hypothesis')

Significnace=0.050, p=0.425
We fail to reject Null hypothesis
